fix: replace & characters in project name to avoid error on platform add
apache/cordova-android pull request #1384
Opened 2021-12-07 19:23 UTC by tiagoappereira

### Platforms affected
Android

### Motivation and Context

Error on `cordova platform add` when the Cordova app name contains the character `&`. The issue occurs when parsing the `strings.xml` file. The issue was introduced on cordova-android 10.1.0

Fixes https://github.com/apache/cordova-android/issues/1380

### Description

Simply replaces the `&` characters in the project name (if present) by an `_`. 

### Testing

`npm test` and project creation successful

### Checklist

- [x] I've run the tests to see all new and existing tests pass
- [x] I added automated test coverage as appropriate for this change
- [x] Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)
- [x] If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))
- [x] I've updated the documentation if necessary

2021-12-07 19:35 UTC, dpogue commented
Wouldn't the correct fix be to XML-escape the `&` (or other special characters like `<` and `>`)?

2021-12-09 16:58 UTC, breautek approved these changes
Lgtm

2021-12-20 17:55 UTC, jcesarmobile requested changes
package.json doesn't include lodash.
It works because there are 3 other dependencies that include lodash as dependency themselves but it could break in the future if those dependencies are replaced/removed or they stop using lodash in a newer version. 
So I think it should be included in the package.json to prevent that.

2022-01-04 12:51 UTC, jcesarmobile approved these changes

2022-01-05 14:49 UTC, erisu requested changes
I am not infavor for installing the entire lodash package just to use one method.

Either install the exact package, lodash.escape, or write our own escape method please.

**Lodash**
package size:  319.0 kB
unpacked size: 1.4 MB

**Lodash Escape**
package size:  3.9 kB
unpacked size: 9.1 kB

2022-01-05 14:59 UTC, jcesarmobile commented
It's already being installed because it's a dependency of other 3 dependencies.
As you can see, the package-lock.json doesn't change because it's already installed.

I would be in favor of not installing lodash, but that would mean updating a lot of our dependencies (including cordova-common as it depends on @netflix/nerror which depends on lodash)

2022-01-05 15:05 UTC, erisu commented
We have been removing lodash from our dependencies because of the vuln. report frequencies.

I have discussed with others on dropping `@netflix/nerror` because they neglected to update their package over 2 years now and even with PRs open to resolve some issues.

https://github.com/Netflix/nerror/pull/18

2022-01-05 15:09 UTC, breautek commented
> We have been removing lodash from our dependencies because of the vuln. report frequencies.
> 
> I have discussed with others on dropping `@netflix/nerror` because they neglected to update their package over 2 years now and even with PRs open to resolve some issues.
> 
> [Netflix/nerror#18](https://github.com/Netflix/nerror/pull/18)

To add onto this, we can probably solve the same issue using the JS native method [encodeURIComponent](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/encodeURIComponent) so that we can avoid introducing another lodash dependency. I'm pretty sure the method exists in NodeJS environments.

2022-01-05 15:17 UTC, jcesarmobile commented
`encodeURIComponent` won't work because it scapes `<Incredible&App>` to `%3CIncredible%26App%3E`, which is not valid on the `strings.xml`.

I solved a similar problem in Capacitor using replace like this
https://github.com/ionic-team/capacitor/pull/5325/files#diff-ed3a1ffe6172324599c40aaeea6832beab33815ec5c28ba7f87e1a37fb55fae1R74-R78

note that it doesn't include `>` replacement because it wasn't needed in Capacitor, but might still be needed in Cordova as it looks like it does some previous conversion
also note that it includes `"`, which is not escaped by lodash

2022-01-05 15:22 UTC, erisu commented
Here is what lodash escape does, just for additional details:

```
  '&': '&amp;',
  '<': '&lt;',
  '>': '&gt;',
  '"': '&quot;',
  "'": '&#39;',
  '`': '&#96;'
```

2022-01-05 15:28 UTC, jcesarmobile commented
there is some previous conversion somewhere else, because I tested with `'` and `"` and `'` was converted to `\'` and `"` wasn't converted at all.
Note that for them to work in `strings.xml` they have to be `\'` and `\"`, didn't try ` (by work I mean that the app name is displayed on the phone exactly as on the `strings.xml`)

2022-01-05 18:58 UTC, jcesarmobile commented
I found where the `'` is converted to `\'`, is not done by lodash

https://github.com/apache/cordova-android/blob/09c75237d9348a944b4946ccb31d2dee90330ce4/lib/prepare.js#L266

2022-02-04 00:22 UTC, erisu approved these changes

2022-02-08 02:29 UTC, merged